chains.yaml

This PR adds Umee, Emoney and Cheqd to the nightly builds.

Adds: Umee Emoney Cheqd

---

chains.yaml
cmd/build.go
dockerfile/none/Dockerfile

Adds language: none Dockerfile for images that don't build from source, e.g. downloading binaries.
Not a recommended chain integration, but some chains are closed source such as injective

Add injective chain

---

chains.yaml

add chain cosmos-hub-ics

---

chains.yaml

cosmos-ics updates

---

chains.yaml

Reverts strangelove-ventures/heighliner#24
No longer necessary with https://github.com/Stride-Labs/stride/pull/255 merged

Revert "Fix stride static build"

---

chains.yaml

Not sure why I skipped this one before. No issues building.

Add Irisnet

---

dockerfile/sdk/Dockerfile
dockerfile/sdk/native.Dockerfile

Reverts strangelove-ventures/heighliner#35

Revert "Bump libwasmvm to 1.1.0"

---

chains.yaml
cmd/build.go
dockerfile/nix/Dockerfile
dockerfile/nix/native.Dockerfile
dockerfile/rust/Dockerfile
dockerfile/sdk/Dockerfile
dockerfile/sdk/native.Dockerfile

Composable switched to using Nix to build their package.
This PR adds support for Nix and updates Composable in the chains.yaml.

Add support for Nix + update Composable

---

chains.yaml

Adding neutron

---

chains.yaml

The wasm runtimes should be bundled with the composable binary

Bundle wasm runtimes with composable

---

chains.yaml

- Successfully tested with version `v0.6.6`

feat(chain): quicksilver chain

---

chains.yaml

Motivation: Strangelove will join the validator set. 
As of this writing, Onomy is not in the chain registry. 😢

Add Onomy to chains.yaml

---

chains.yaml

**This will only work above AssetMantle node version `v0.3.0`**

feat(chain): AssetMantle chain

---

chains.yaml

update injective binaries

---

chains.yaml

add nibiru

---

chains.yaml

We're working on an IBC middleware and IBC-enabled module and would love to get more tightly integrated with heighliner/ibctest!

Add burnt chain

---

chains.yaml

~~I tackled this issue all morning getting an Axelar build to work on the heighliner VM.~~ Fixed in https://github.com/strangelove-ventures/heighliner/pull/102
Also added notes about red herrings (protoc + nodejs) versions.

docs: Add special notes for Axelar

---

builder/builder.go
chains.yaml
cmd/build.go
cmd/queue.go
dockerfile/cargo/Dockerfile
dockerfile/cargo/native.Dockerfile
dockerfile/cosmos/Dockerfile
dockerfile/cosmos/local.Dockerfile
dockerfile/cosmos/native.Dockerfile

Add `--race` flag to enable race detection in chain node binary for cosmos Dockerfile builds
`heighliner build -c gaia -g v8.0.0 --race`
Resulting image: `gaia:v8.0.0-race`

add --race flag

---

chains.yaml

added quasar binary to heighliner

---

chains.yaml

new release, new build process

new release, new repo

---

chains.yaml

added testnetx

---

chains.yaml

Some of the agoric go deps did not have prebuilts for arm64
resolves #132

fix agoric for arm64

---

chains.yaml

Reverts strangelove-ventures/heighliner#138
I already patched arm64 in #137

Revert "fix: Agoric build for linux/amd64"

---

docker/buildkit.go

make sure image tags are present in tar export

common attrs for tar export

---

builder/builder.go

ignore lint error for signal.Notify

---

builder/go_versions.go
builder/go_versions_test.go

Added support for go 1.21.0 and set it to be default.

Added support for go 1.21.0 and set it to be default.

---

chains.yaml

https://github.com/White-Whale-Defi-Platform/migaloo-chain

Add migaloo chain

---

chains.yaml

Should build celestia-node instead of celestia-app

Celestia node build

---

builder/builder.go
chains.yaml
dockerfile/cosmos/Dockerfile
dockerfile/cosmos/local.Dockerfile
dockerfile/cosmos/localcross.Dockerfile
dockerfile/cosmos/native.Dockerfile

If chain is using fork of libwasmvm, download from that repo's releases.
Thanks to @PFC-developer for helping to resolve this issue!

Should work with wasmvm forks

---

dockerfile/avalanche/Dockerfile
dockerfile/avalanche/native.Dockerfile
dockerfile/cargo/Dockerfile
dockerfile/cargo/native.Dockerfile
dockerfile/cosmos/Dockerfile
dockerfile/cosmos/local.Dockerfile
dockerfile/cosmos/localcross.Dockerfile
dockerfile/cosmos/native.Dockerfile
dockerfile/imported/Dockerfile

Update toolkit version

---

chains.yaml

Reverts strangelove-ventures/heighliner#223

Revert "Axelar v0.35 wasm requirements update"

---

builder/builder.go

fix(CosmWasm package): Trim CosmWasm /v2 suffix from package string pulled from go mod

---

chains.yaml

generate binary was removed from thornode repo

fix: remove generate build from thorchain

---

chains/lava.yaml

Add lava chain to build heighliner images.

feat: add lava chain

---

chains/elys.yaml

Add Elys binary building settings

feat: Create elys.yaml

---

chains/sei.yaml

fix: put seid binary back

---

chains/sei.yaml

Reverts strangelove-ventures/heighliner#308

fix: Revert "fix: put seid binary back"
