chains.yaml
Adds: 
- chihuahua
- kichain
- panacea
- shentu
- sifchain
- vidulum
=> Add chains to image builds

busybox.min.config, dockerfile/sdk/Dockerfile, dockerfile/sdk/native.Dockerfile
I missed this today. Unfortunately, k8s doesn't easily let you see Volume used disk space, only the capacity.
I don't *think* `du` is a security risk. If so, please close this PR with a reason (so I'm educated!).
=> feat: Add du to images

chains.yaml, dockerfile/rust/Dockerfile
This PR:
- adds the ability for `language: rust` chains to accept empty build targets
- copies "lib" folder into Debian image 
- Adds Carbon Chain
Seems like `crossarch.Dockerfile` is un-used at the moment. Did not touch that file. Plus we are planning to start building docker images "from scratch"
Closes: https://github.com/strangelove-ventures/heighliner/issues/17
=> Accept Empty Build Targets for Rust images and Add Carbon Chain

dockerfile/sdk/Dockerfile, dockerfile/sdk/native.Dockerfile
No trusted CA root certs are present in the images now, so commands against TLS-secured remote nodes were not working:
```bash
$ docker run -it --rm --entrypoint osmosisd ghcr.io/strangelove-ventures/heighliner/osmosis:v11.0.1 q gov proposals --node https://rpc.osmosis.strange.love:443
Error: post failed: Post "https://rpc.osmosis.strange.love:443": x509: certificate signed by unknown authority
```
This brings over the alpine linux trusted CA list into the final images
=> Include trusted CA certs

chains.yaml
For consistency, these names should be updated to match the `chain_name` on the chain registry.
=> Update chain names to match chain-registry

dockerfile/nix/Dockerfile, dockerfile/nix/native.Dockerfile, dockerfile/rust/Dockerfile, dockerfile/sdk/Dockerfile, dockerfile/sdk/native.Dockerfile
Chains that used a relative path to the binary from the build directory were broken by #42 
Fixes #46
=> Fix relative path binary copy

README.md, cmd/build.go, cmd/root.go, docker/docker.go, dockerfile/dockerfiles.go, dockerfile/sdk/local.Dockerfile, main.go
Enables heighliner standalone builds:
- Use `heighliner` bin in any working directory, does not need to find `chains.yaml` or any of the dockerfiles from the root of the repo anymore
- Adds `--local` flag which can be used for building from a local directory instead of a remote github repository. Useful for chain development cycles.
Docker requires that the Dockerfile used for building be within the build context directory. It cannot be in a parent directory or other path. To enable local builds, heighliner now has the dockerfiles embedded within the binary. It will look for the local dockerfile, but use the embedded dockerfile if it cannot be found. It will write the applicable dockerfile into a temporary directory within the local repo, then delete after build completion (success of …
=> Standalone phase 2. 

chains.yaml, dockerfile/rust/Dockerfile, dockerfile/rust/native.Dockerfile, dockerfile/sdk/Dockerfile, dockerfile/sdk/native.Dockerfile
PR into @danbryan 's working branch for adding tofnd. Simplifies build to use heighliner built-in clone and build process rather than manually using pre-build. Fixes build for arm64.
=> Recursive clone in Dockerfiles, use build target for tofnd

chains.yaml, dockerfile/rust/Dockerfile, dockerfile/rust/native.Dockerfile, dockerfile/sdk/Dockerfile, dockerfile/sdk/native.Dockerfile
=> chain info for tofnd

dockerfile/sdk/Dockerfile, dockerfile/sdk/local.Dockerfile, dockerfile/sdk/native.Dockerfile
Only check final versions of libs for wasm version check. This reduces the time to check for the wasm version when building the Dockerfile significantly.
https://stackoverflow.com/questions/59196227/find-version-of-a-module#answer-59244274
=> optimize wasm version check

chains.yaml, dockerfile/sdk/Dockerfile, dockerfile/sdk/local.Dockerfile, dockerfile/sdk/native.Dockerfile
Allow non-make builds for SDK by requiring `build-target` to be the full build command.
This also allows multi-line `build-target` instructions, so chains that were previously configured to build everything in `pre-build` can now use `build-target`
=> Remove dependency on Makefile

builder/builder.go
Go version needs to check a local file, not a git cloned file, when `--local` is set.
=> Fix go version check for local builds

README.md, builder/builder.go, cmd/build.go, cmd/queue.go
Allows overriding all of the chains.yaml parameters.
This makes it possible to override params without needing to modify chains.yaml, or build chains that aren't present in chains.yaml if all necessary flags are provided.
Resolves #45
=> chain config override flags

chains.yaml
Onomy merged the PR mentioned in the note. Builds should now work as intended.
=> docs: Remove Onomy special note

dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile, dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/native.Dockerfile
Bump infra-toolkit to [v0.0.7](https://github.com/strangelove-ventures/infra-toolkit/releases/tag/v0.0.7) and bring in [new utils](https://github.com/strangelove-ventures/infra-toolkit/pull/7)
=> Add extra utils

builder/builder.go, builder/go_versions.go, builder/go_versions_test.go, chains.yaml, dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile, dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/native.Dockerfile, dockerfile/none/Dockerfile, go.mod
- Add Sei chain as a cargo build dockerfile type since it requires glibc
- cleanup dockerfiles
- Add go.mod lookup for cargo dockerfile also. install golang for building if go.mod exists.
- Add `set -eux` to all dockerfile script steps to catch any errors along the way instead of proceeding past them.
=> Add sei chain

README.md, cmd/queue.go
Unauthenticated requests are limited to 60 requests per hour. This increases to 1000 per hour per repo for personal accounts, and 15000 for enterprise accounts.
Adds `GH_USER` and `GH_PAT` env vars to authenticate to Github API when fetching recent releases
Resolves #47
=> Github releases API auth

dockerfile/cosmos/local.Dockerfile
Closes #106
Drastically improves local Dockerfile compile time by installing all base unix binaries & libs before compiling final image.
We are seeing 30-35+ minute docker build times on Juno with https://github.com/CosmosContracts/juno/pull/597. This is due to `ADD` being one of the first steps in the file, not allowing for any future step caching. This PR moves that to the end, and caches better. Which drastically improves compile time for testing
```sh
go install # heighliner this PR
heighliner build -c juno --local -f ./chains.yaml # first 37/48 steps cached
cd juno
make ictest-upgrade # runs local test
```
=> Optimize local.Dockerfile compile times drastically

cmd/build.go, cmd/list.go, cmd/root.go
A sample of the new output:
```
Loaded chains from /Users/davidnix/src/strangelove/heighliner/chains.yaml
acrechain:
cosmos-sdk@v0.45.10
ibc-go@v3.2.0
agoric:
error: not enough repo info; missing organization or repo
akash:
error: GET https://raw.githubusercontent.com/ovrclk/akash/main/go.mod: 404 Not Found
assetmantle:
error: GET https://raw.githubusercontent.com/assetmantle/node/main/go.mod: 404 Not Found
axelar:
cosmos-sdk@v0.45.11
ibc-go@v4.2.0
```
=> refactor: Improve list subcommand error reporting

cmd/list.go, go.mod, go.sum
Sample output:
```
[...]
wasm:
cosmos-sdk@v0.47.0
ibc-go@v7.0.0
Summary:
cosmos-sdk versions:
0.1 (1)
0.4 (1)
0.42 (1)
0.44 (2)
0.45 (25)
0.46 (9)
0.47 (3)
1.0 (3)
total: 45 chains
ibc-go versions:
1.2 (1)
2.0 (2)
3.0 (2)
3.2 (1)
3.3 (3)
3.4 (5)
4.2 (7)
4.3 (8)
5.1 (1)
5.2 (4)
6.1 (3)
7.0 (1)
total: 38 chains
```
=> Add stats on cosmos/ibc versions to list command

addChain.md, builder/builder.go, builder/types.go, chains.yaml, dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile
Penumbra `pclientd` binary requires `libnss_dns.so.2` and `libresolv.so.2` in order to resolve DNS.
Adds `target-libraries` to config for copying libraries from the target image.
=> Target libraries - fix penumbra dns

chains.yaml
We've rebranded our network from Burnt chain to Xion for our public launch and upgraded to the latest cosmos-sdk (v0.47.0). Updating the chains manifest to reflect.
=> Add Xion chain

chains.yaml
This PR adds both the Kaon (KYVE's official testnet) and KYVE networks.
We had one issue with our Makefile, which is being remedied in https://github.com/KYVENetwork/chain/pull/34, and being released as `v1.1.1`
Until this is done, you can use [`john/v1.1-heighliner`](https://github.com/KYVENetwork/chain/tree/john/v1.1-heighliner) to verify the images.
=> feat: add KYVE networks

dockerfile/avalanche/Dockerfile, dockerfile/avalanche/native.Dockerfile
Avalanchego writes some temporary files into `/tmp` directory. If it doesn't exist then node stops
=> Add tmp folder to Avalanche image

chains.yaml
A bad chains.yaml crushes Heighliner
```
$ heighliner build -h
panic: error parsing chains.yaml: yaml: line 48: could not find expected ':'
goroutine 1 [running]:
github.com/strangelove-ventures/heighliner/cmd.Execute({0x16fa440?, 0xda41c0?, 0xc000002340?})
/home/strangelove/heighliner/cmd/root.go:17 +0x145
main.main()
/home/strangelove/heighliner/main.go:13 +0x2e
```
=> fix: Malformed chains.yaml

chains.yaml
Their `make` requires additional dependencies. They also moved their org and repo.
=> fix: Update akash in chains.yaml

dockerfile/cosmos/local.Dockerfile
I did not catch this in review of #107 , but `libraries` from `chains.yaml` should be copied after the build is complete. The intended use case of this is if shared libraries need to be built as part of the build target.
=> fix: cosmos local dockerfile libraries

chains.yaml
Addresses https://github.com/strangelove-ventures/heighliner/issues/132
Per suggestion in the above issue. 
This is my preference, to have `heighliner build` work (even partially) without having to remember command line flags. And the comment memorializes the issue and decision in the codebase vs. hunting through PR history.
=> fix: Agoric build for linux/amd64

builder/builder.go, builder/types.go, cmd/build.go, docker/buildkit.go
Adding flag `--tar-export-path` will make heighliner with buildkit output to a docker-compatible tarball instead of pushing to a registry. This only works if building for a single arch.
=> add feature to export to docker tarball

dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/native.Dockerfile
Grabs the last field of wasmvm version grepped instead of the 2nd. This ensures a replace in go.mod will pull the correct version.
I noticed the latest osmosis builds do not work because wasmvm v1.1.1 is downloaded instead of v1.1.2. Here is the error:
Error: libwasmversion mismatch. got: 1.1.1; expected: v1.1.2
You can see the replace here along with the security advisory. For indirect dependencies, the advisory recommends using a replace, so this commit could be required for more chains following that guidance too:
https://github.com/osmosis-labs/osmosis/blob/v15.1.2/go.mod#L314
=> Wasmvm version awk should pull the last field

chains.yaml
This updates the sei chains.yaml config to better reflect changes that have been made in the sei build process more recently.
Tested by building sei image with the commands and verified that the binary is runnable in the container
```
./heighliner build -c sei -g 3.0.5
docker run -it --rm --entrypoint sh sei:3.0.5
```
=> update sei config in chains.yaml

cmd/queue.go
Status check to ensure we receive a 200 before proceeding to build an image.
=> Add status check to ensure we gracefully discontinue

chains.yaml
quasar is now at quasar, not quasar-preview.  github did not seem to link these, so an update to heighliner is needed
=> fix for quasar

chains.yaml
Kafka is no longer required for building Provenance (thankfully).
=> Update Provenance config to remove Kafka dependency

builder/builder.go, chains.yaml
The lookup now does not error if there is no go.mod. Most cargo setups do not have a go.mod.
=> Add hyperlane agent support. Fix non-cosmos/non-avax go version lookup.

builder/builder.go, builder/go_versions.go, builder/go_versions_test.go, builder/types.go, cmd/build.go
Resolves #162 for stubborn chains
=> Add go and alpine version overrides

chains.yaml, dockerfile/imported/Dockerfile
Make imported build work for base images that don't have a shell
Resulting image is now standard scratch image with all of the usual utils
=> Make imported builds more heighliner-y

chains.yaml
This PR adds SubnetEVM (with IBC) binary into docker image. This eliminates additional work to build SubnetEVM and then copy into container
=> Add SubnetEVM with IBC into Avalanche docker image

builder/go_versions.go
add go 1.22, bump alpine to 3.19, and bump prior versions
=> bump versions

chains.yaml
Replay axelar wasm changes after confirming axelar builds on alpine version 3.18
=> Axelar v0.35 wasm support - replay previous PR

README.md
README.lint offers a convention-over-configuration approach to README files, simplifying onboarding to a new tech stack.
More at https://github.com/strangelove-ventures/readme-dot-lint.
=> refactor(readme): Make README.lint conformant.

builder/builder.go, builder/types.go, cmd/build.go, cmd/queue.go, dockerfile/cosmos/Dockerfile, dockerfile/cosmos/native.Dockerfile
This PR adds support for a new `clone-key` option, allowing Heighliner to build private repositories.
This is useful when testing internal SimApps.
Note that this is a copy of #249, which was closed because the branch was automatically deleted.
=> feat: add `clone-key` option for private repos

dockerfile/cosmos/Dockerfile, dockerfile/cosmos/native.Dockerfile
Also tagging @boojamya and @johnletey for visibility (want to make sure this was the intention).
=> fix: Patch bad reference to clone key variable in dockerfile/cosmos

dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/localcross.Dockerfile
It is possible that local repo can have private go modules in the go.mod, add CLONE_KEY option in local*.Dockerfile if required.
Also `WORKDIR /go/src/${REPO_HOST}/${GITHUB_ORGANIZATION}/${GITHUB_REPO}` should be created before `ADD . .`
=> feat: add clone-key option for local with private go modules

README.md, dockerfile/cosmos/Dockerfile
1. Remove link to private repo that is causing a lint error.
2. Some chains name static wasm lib file's differently
=> fix: Some chains decide to name the static files differently

builder/go_versions.go
Reference: https://hub.docker.com/_/golang
Note: according the above reference, we could probably get away with removing the minor version and just have `1.22` to always pull latest if we wanted to.
=> chore: update latest go version `1.22.6`

chains.yaml
it appears to have been accidentially re-added in a previous pr
=> fix: re-remove generate binary from build as it was removed from thornode repo

dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/localcross.Dockerfile, dockerfile/cosmos/native.Dockerfile
dir copy works if the dir path already exists in the final image, but not otherwise
=> fix: support creating dirs for copied directories

chains/terra-classic.yaml
split didn't create terra file.
and terra now is run from phoenix-directive repo
=> fix: switcharoo on terra/terra-classic

builder/builder.go, docker/docker.go, dockerfile/cosmos/local.Dockerfile, go.mod, go.sum
When using the --local flag, this adds support for chains that choose to vendor all their Go dependancies.
Also updates docker.
=> feat: detect "vendor" folder for local builds

chains/axone.yaml
Add [Axone](https://github.com/axone-protocol/axoned) chain to build `heighliner` images.
Thx 🙏
=> feat: add axone chain

go.mod
Going to make modifications for future features.
Need golang 1.23 for those.
=> chore: update golang version

dockerfile/avalanche/Dockerfile, dockerfile/avalanche/native.Dockerfile, dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile, dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/localcross.Dockerfile, dockerfile/cosmos/native.Dockerfile, dockerfile/imported/Dockerfile
This PR is for adding useful utilities to the chain docker images ( mkdir, vi, rm and mv)
**_Ref_**: [301](https://github.com/strangelove-ventures/heighliner/issues/301)
- Install / Enable necessary applet 
- rm (for cleanup)
- mv (for moving / renaming files)
- mkdir (for creating directories)
- vi  (for editing files')
- Prevent those write utils from being removed
- While preparing the test, I grouped the chains into 4 categories : 
- avalanche
- cargo
- cosmos
- imported
- And for each of those categories , I had to run a test.
- **_avalanche_**
- **Chain:** avalanche
- **Image:** ghcr.io/strangelove-ventures/heighliner/avalanche:v1.11.11-utility 
- **_cargo_**
- **Chain:** neutron
- **Image:** ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.5-utility
- **_cosmos_**
- **Chain:** …
=> feat: add useful utilities to the chain docker images 

chains.yaml, dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile
Required for Cosmos chains like Neutron, which are built with cargo and based on SDK v0.50.x.
=> Add tmp dir to cargo dockerfiles

.github/workflows/lint.yml
This PR to fix a test issue encountered in a bump PR https://github.com/strangelove-ventures/heighliner/pull/316
- Add go mod tidy to the pipeline as the errors stated
`level=error msg="Running error: context loading failed: no go files to analyze: running `go mod tidy` may solve the problem"
27`
- Will run the bump PR to see if this is fixed
- N/A
=> fix: add go mod tidy command to solve the bump test failure

dockerfile/avalanche/Dockerfile, dockerfile/avalanche/native.Dockerfile, dockerfile/cargo/Dockerfile, dockerfile/cargo/native.Dockerfile, dockerfile/cosmos/Dockerfile, dockerfile/cosmos/local.Dockerfile, dockerfile/cosmos/localcross.Dockerfile, dockerfile/cosmos/native.Dockerfile, dockerfile/imported/Dockerfile
This PR is for removing busybox-full to fix the possible exposure to vulnerabilities through having utilities
- Remove busybox-full image
- Update Dockerfile to copy core utilities (rm, mv, ln, vi, jq) from the custom BusyBox build in infra-toolkit.
- Ensure that all binaries (except jq and specific chain binaries) share the same inode, meaning they are hard links to a single minimal busybox binary.
- Save disk space and limit exposure to unnecessary utilities.
- N/A
- The new infra-toolkit Image  will be used in the Dockerfile ( it will have the binaries )
**Busybox Hardlink Optimization & Security Considerations**
The goal is to ensure that all binaries (except `jq` and chain-specific binaries) are hard links to a single minimal `busybox` binary. This helps to:
- Reduce disk space …
=> fix: remove busybox-full bins from the final image

chains/penumbra.yaml
The upstream release of Penumbra v1.5.0 [0] introduced optional USB dependencies in their Rust workspace, as part of Ledger support. Although the relevant USB-consuming features are off by default, running `cargo build --release` will build all crates in the workspace, including the new Ledger crates, even though they're not used in any binaries by default. Instead, let's use `cargo build --release --bins` in the heighliner config, so that strict dependency resolution is used within the Penumbra workspace, ensuring that the disabled features are not enabled.
[0] https://github.com/penumbra-zone/penumbra/releases/tag/v1.5.0
=> fix: penumbra build for v1.5.0
